# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hHKJXqye6kwU5FDmj-jjA2n9k3ISR-uM

Python Chapter 2 : variable and simple data types
"""

print("Hello Python World!")

message = "Hello Python World!"
print(message)
message = "Hello Python Crash course reader"
print(message)

'''
-prompt rackets (>>>)
-how to use command menu, command prompt
-naming and using variables
'''

print("Hello Python interpreter!")

#strings
"This is a string"
'This is also a string'
#changing case with string methods
#run cell with control + enter
'I told students, "Read the chapter ahead of time" '
"The language 'python' is named after Monty Python, not the snake"

name = "Ada Lovelace"
print(name.title())
# The title()method changes each word to title case, which each word begins with capital letter

#adding variables in strings, F string {} (fancy bracket)
first_name = "ada"
last_name = "lovelace"
full_name = f"{first_name} {last_name}"
print(full_name)
print(f"hello, {full_name.title()}!")

#adding white space to stings : nonprinting characters
print('Python')
print('\tPython')
#\n = new line
print("Languages:\nPython\nC\njavaScript")

print("Languages:\nPython\n\tC\njavaScript")

#stripping whitespace
fav_lang = 'python'
fav_lang
# R stripe method (Eliminate whitespace on right side)
fav_lang.rstrip()
fav_lang = fav_lang.rstrip()

#L strip (Removes whitespace permanently)
fav_lang
fav_lang.lstripe()
fav_lang.strip()

url = "https://www.google:8080)"
url.removeprefix('http://')
url.removesuffix(':8080')
url = url.removeprefix('https://').removesuffix(':8080')
url

"""Exercise (try it yourself)"""

from re import X
#personal message 2-3
print("hello, Eric, would you like to learn some python today")

#name cases 2-4
name = "joe"
print(name.title())
print(name.upper())
print(name.lower())

#famous quote 2-5 
print("Travis scott once said 'it's lit' ")

#famous quote 2-6
message = "Travis scott "
print(message + "once said 'it's lit' ")

#stripping names 2-7
Name = "joe"
print(Name)
print("\tName")
print("\nName")
print(name.lstrip())
print(name.rstrip())
print(name.strip())

#file extensions 2-8
filename = 'python_notes.txt'
filename.removesuffix('txt')


# Number eight 2-9
print(2 ** 3)
print(1 + 7)
print(2 * 4)

# favorite number 2-10 
favorite_number = 66
print('my favorite number is ' + str(favorite_number))

#numbers
2 + 3
3 - 2 
2 * 3
3 / 2
3 ** 2
3 ** 3
10 ** 6 
2 + 3 * 4
(2 + 3) * 4

#floats 
0.1 + 0.1
3.0 * 0.1


 #underscore 
million = 1_000_000
million
billion = 1000_000_000
billion
