# -*- coding: utf-8 -*-
"""chapter3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YN9_63N6wwZgYBhghf0hpIPegjXKsxJ1
"""

genres = ['pop', 'rock', 'rap', 'indie']
print(genres)

print(genres[0])

print(genres[0].title())

# "genres" is considered an element in this case
print(genres[1])
print(genres[3])
print(genres[-1])
# wrap in f string (curly braces ???)
message = f'My favorite genre is {genres[0]}'

genres[0] = 'edm'
#append puts variable at the end of the list
genres = []
genres.append('edm')
genres.append('rock')
genres.append('rap')
genres.append('indie')
genres.append('jazz')
genres

#List method used to add an element to the end of a list.

#insert method : puts variable in front of list
genres.insert(0, 'classical')
genres

#remove variable if you know the location
del genres[0]
genres
#If you know the position of the item you want to remove from a list, you can use the del statement.

genres = ['pop', 'rock', 'rap', 'indie','jazz']
genres.pop()
genres
#pop() removes "jazz" from end of the list, (last variable) 
#Method used to remove item from any position in a list and then use that value after it has been removed.

genres = ['edm', 'rock', 'rap', 'indie', 'jazz']
least_favorite = genres.pop() 
#if you insert value inside parenthesis, it will remove the ordered variable in the list
print(f'I don\'t like', least_favorite)

#remove variable
genres = ['edm', 'rock', 'rap', 'indie', 'jazz']
genres.remove('jazz')
genres

#try it yourself, invite someone to dinner (3 people), then change the list 
name = ['joe', 'bob', 'frank','emily']
print(name)

#set value to a specific variable in the list
message = ', please bring me some food'
print(f'{name[2]} {message}')

#set value to a specific variable + f string
cars=['honda', 'toyota', 'ford', 'dodge']
print(f'I would like to own a {cars[3]} automobile')
guests = ['Buddha', 'Socrates', 'Mohammed', 'Jesus', 'Abraham']
print(f'dear {guests[0]} please come to dinner')
print(f'dear {guests[1]} please come to dinner')
print(f'dear {guests[2]} please come to dinner')
print(f'dear {guests[3]} please come to dinner')
print(f'dear {guests[4]} please come to dinner')
decline = guests.pop(3)
print(f'sadly, {decline} can\'t make it.')

guests.insert(0,'juan')
guests.insert(2, 'sandra')
guests.append('jupiter')
print(f'dear {guests[0]} please come to dinner')
print(f'dear {guests[1]} please come to dinner')
print(f'dear {guests[2]} please come to dinner')
print(f'dear {guests[3]} please come to dinner')
print(f'dear {guests[4]} please come to dinner')

len(guests)

guests = ['Buddha', 'Socrates', 'Mohammed', 'Jesus', 'Abraham']
print(f'dear {guests[0]} please come to dinner')
print(f'dear {guests[1]} please come to dinner')
print(f'dear {guests[2]} please come to dinner')
print(f'dear {guests[3]} please come to dinner')
print(f'dear {guests[4]} please come to dinner')
print("i can only invite two people")
person = guests.pop()
print(f"sorry, {person} I don't have room.")
person = guests.pop()
print(f"sorry, {person} I don't have room.")
person = guests.pop()
print(f"sorry, {person} I don't have room.")

print(f'dear {guests[0]} please come to dinner')
print(f'dear {guests[1]} please come to dinner')

del guests[1]
del guests[0]
guests

#try it yourself 3.8
places = ['australia', 'turkey','laos', 'thailand','hawaii']
# print(f"I would like to visit {places[0]}")
# print(places)
# print(sorted(places))
# print(places)
# places.reverse()
# print(places)
# places.reverse()
# print(places)
# places.sort()
# print(places)
# places.sort(reverse=True)
# print(places)

places = sorted(places)
places.reverse()
print(places)

''' word bank 
The ________ function lets you display your list in a particular order, but doesn’t affect the actual order of the list.  sorted()
A ____ is a collection of items in a particular order.                                                                    list
The ______ method changes the order of the list permanently.                                                              .sorted()
You can access any element in a list by telling Python the position, or _____, of the item desired.                       index
You can quickly find the length of a list by using the _____ function.                                                    len()
List method used to add an element to the end of a list.                                                                  .append()
List method used to insert an element at any position in a list.                                                          .insert()
If you know the position of the item you want to remove from a list, you can use the ___ statement.                         del 
If you only know the value of the item you want to remove, you can use the ________ method.                               .remove()
Method used to remove item from any position in a list and then use that value after it has been removed.                   .pop()
'''

#organizing the list with sort()
genres = ['edm', 'rock', 'rap', 'indie', 'jazz']
genres.sort()
genres

genres = ['edm', 'rock', 'rap', 'indie', 'jazz']
print(sorted(genres))
print(genres)
#printing without sorted

#permanently print with sorted order, reverse(), this is a method !!!!!
genres = ['edm', 'rock', 'rap', 'indie', 'jazz']
genres.reverse()
genres

#length (how many variables are in the list)
len(genres)

#Try it yourself, exercise. college board project requires list, variables in list, loop, list manipulations, etc, (written portion need to select used method)
#length               len()
#remove               remove()
#remove from location pop()
#reverse              reverse()
#replace              index()
#
