# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZlXYFNqqbPhmUXOneM8TwWLZMEn7FTj6
"""

'''chapter 4 notes 
-loop in a list
-loop with f string
-action after loop is performed
'''

#for loop in a list
magicians = ['joe', 'bob', 'frank']
for magician in magicians:
 print(magician)

#general list in list items
cats = ['a','b','c']
for cat in cats:
  print(cat)
items_in_list = ['a','b','c']
for items in items_in_list:
  print(items)

#f string in a for loop
magicians = ['joe', 'bob', 'frank']
for magician in magicians:
  print(f"{magician.title()}, text")
  print(f"I can't wait to see your next trick, {magician.title()}.\n")
  # \n is a blank after every loop

#actions after a for loop
magicians = ['joe', 'bob', 'frank']
for magician in magicians:
  print(f"{magician.title()}, text")
  print(f"I can't wait to see your next trick, {magician.title()}.\n")
#edit actions without indentation from the printed value. 
print("hi")

"""**Try it yourself practices**"""

#4-1:pizzas 
pizzas = ['pepperoni', 'sausage', 'mushroom']
for pizza in pizzas:
  print(f"i like {pizza.title()}")
print("I love pizza so much")

#4-2:animals
animals = ['tiger', 'lion', 'kangaroo']
for animal in animals:
  print(animal)
  print(f"{animal} would be a good predator")

#making numeral lists 

for value in range(1, 5):
  print(value)
#range() function, the example only prints 1,2,3,4 because it stops at the second off last value
for value in range(1, 6):
  print(value)
#this example bellow will print range(0,6)
print(range(6))

#wrap range function in a list
numbers = list(range(1, 6))
print(numbers)
#skip certain numbers in a list, this will print all the even numbers inside the range 
even_numbers = list(range(2, 11, 2))
print(even_numbers)
#printing all the squared numbers 
square_list = []
for value in range(1, 11):
  square_value = value ** 2
  square_list.append(square_value)
print(square_list)

#4-2simple stat with list 
squares = [value**2 for value in range (1, 11)]
print(squares)

#4-3 counting to twenty
for value in range(1, 21):
  print(value)

#4-4 count to one million 
for value in range(1, 1000001):
  print(value)

from re import L
#4-5 summing a million 
''' 4-5. Summing a Million: Make a list of the numbers from one to one million, 
and then use min() and max() to make sure your list actually starts at one and ends
at one million. Also, use the sum() function to see how quickly Python can add
a million numbers.'''

numbers = list(range(1, 1000001))
print(min(numbers))
print(max(numbers))
print(sum(numbers))

#4-6 odd numbers
for value in range(1, 21):
  print(value)

'''4-7. Threes: Make a list of the multiples of 3, from 3 to 30. Use a for loop to
print the numbers in your list.'''
threes = list(range(3,31,3))
for three in threes :
  print(three)

'''4-8. Cubes: A number raised to the third power is called a cube. For example,
the cube of 2 is written as 2**3 in Python. Make a list of the first 10 cubes (that
is, the cube of each integer from 1 through 10), and use a for loop to print out
the value of each cube.'''
cubes = []
for value in range(1, 11):
  cubes.append(value **3)
for cube in cubes:
  print(cube)

#list comprehension
cubes = [value ** 3 for value in range(1, 11)]
cubes

'''
 4-10. Slices: Using one of the programs you wrote in this chapter, add several
lines to the end of the program that do the following:
• Print the message The first three items in the list are:. Then use a slice to
print the first three items from that program’s list.
• Print the message Three items from the middle of the list are:. Then use a
slice to print three items from the middle of the list.
• Print the message The last three items in the list are:. Then use a slice to
print the last three items in the list'''

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(f'the first three are {letters[:3]}')
print(f'the middle three are {letters[2:5]}')
print(f'the last three are {letters[-3:]}')

#4-11:my pizzas, your pizzas
my_pizza = ['pepperoni', 'sausage', 'mushroom']
friend_pizzas = ['pepperoni', 'sausage', 'mushroom']
friend_pizzas.append("pinnaple")
print(f'my favorite pizza are {my_pizza}')
print(f'my friend\'s favorite pizza are{friend_pizzas}')

#4-12
#foods.py
my_foods = ['pizza', 'falafel', 'carrot cake']
for foods in my_foods:
  print(f"my favorite foods are: {my_foods}")

friend_foods = ['fries', 'lemon', 'chips']
for stuff in friend_foods:
  print(f"My friend/'s favorite foods are: {friend_foods}")

#4-13
foods = ('hamburger', 'fries', 'salad', 'chicken', 'sushi')
#foods.append('apples')
print("Original menu:")
for food in foods:
    print(foods)
foods = ('cheese', 'queso', 'banana', 'sandwich','beef')
print("\nModified menu:")
for new in foods:
    print(foods)
