# -*- coding: utf-8 -*-
"""chapter5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mw90zytJybD8-FQJJxwcBwjyZGbm-X5K
"""

cars = ['audi', 'bmw', 'sabaru', 'toyota']
for car in cars: 
    if car == 'bmw':
        print(car.upper())
    else:
        print(car.title())

#checking equality
car = 'bmw'
car == 'bmw'
car = 'audi'
car == 'bmw'

'''
2. ignoring case when checking for equality 
'''
car = 'Audi'
car.lower() == 'audi'

age = 18
age == 18

anwser = 17
if anwser != 42:
  print("wrong number")

age_0 = 22
age_1 = 18
age_0 >= 21 and age_1 >= 21
age_1 = 22
age_0 >= 21 and age_1 >= 21


(age_0 >= 21) and (age_1 >= 21)

banned_users = ['andrew', 'carolina', 'david']
user = 'marie'
if user not in banned_users:
 print(f"{user.title()}, you can post a response if you wish.")

game_active = True
can_edit = False

#elif statement

age = 12
if age < 4:
 print("Your admission cost is $0.")
elif age < 18:
 print("Your admission cost is $25.")
else:
 print("Your admission cost is $40.")

#elif statement inside function (list) with print statements
cars = ["one", "two", "three"]
lish = []
for item in cars:
  if item == "one":
    print("one lol")
  else:
    print("not one")
    lish.append(item)

for item in lish:
  print("idk")

#cheking empty list 
toppings = []
if toppings:
  for topping in toppings:
    print(f'adding {topping}')
else:
    print("are you sure ?")

#if-elif-else block
requested_toppings = ['mushrooms', 'extra cheese']
if 'mushrooms' in requested_toppings:
 print("Adding mushrooms.")
elif 'pepperoni' in requested_toppings:   #would only print one of the statements
 print("Adding pepperoni.")
elif 'extra cheese' in requested_toppings:
 print("Adding extra cheese.")
print("\nFinished making your pizza!")