# -*- coding: utf-8 -*-
"""pccc7-2023-03-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QzniD8yKT3ED3rfVzMcy40htvmcrXl7x

# USER INPUT AND WHILE LOOPS
---

### How the `input()` Function Works
"""

# example
message = input("tell me something, and I will repeat it back to you: ")
print(message)

# Writing Clear Prompts

# Using int() to Accept Numerical Input

# The Modulo Operator

"""### TRY IT YOURSELF
---

**7-1. Rental Car:**   
Write a program that asks the user what kind of rental car they would like. Print a message about that car, such as “Let me see if I can find you a Subaru.”
"""

# code
message = input("what kind of rental car would you like? ")
print("let me see if I can find you a", message)

"""**7-2. Restaurant Seating:**   
Write a program that asks the user how many people are in their dinner group. If the answer is more than eight, print a message saying they’ll have to wait for a table. Otherwise, report that their table is ready.
"""

# code
message = int(input("how many people are in your dinner group?" ))
if message > 8:
    print("You will have to wait for a table")
else:
    print("Your table is ready")

"""**7-3. Multiples of Ten:**   
Ask the user for a number, and then report whether the number is a multiple of 10 or not.
"""

# code
number = int(input("what is your number"))
if number % 10:
  print("no")
else:
  print("yes")

"""### Introducing `while` Loops
---

"""

# The while Loop in Action

# Letting the User Choose When to Quit

# Using a Flag

# Using break to Exit a Loop

# Using continue in a Loop

# Avoiding Infinite Loops
x = 1
while x <= 5:
    print(x)

"""### TRY IT YOURSELF
---

**7-4. Pizza Toppings:**   
Write a loop that prompts the user to enter a series of pizza toppings until they enter a `'quit'` value. As they enter each topping, print a message saying you’ll add that topping to their pizza.
"""

# code
while True:
    topping = (input("please enter a pizza topping or quit to exit" ))
    if topping == 'quit':
        break
    print(f"Adding {topping} to your pizza!")

"""**7-5. Movie Tickets:**   
A movie theater charges different ticket prices depending on a person’s age.   
If a person is under the age of 3, the ticket is free;   
if they are between 3 and 12, the ticket is $10; and   
if they are over age 12, the ticket is $15.   
Write a loop in which you ask users their age, and then tell them the cost of their movie ticket.
"""

# code
while True:
    age = int(input("how old are you" ))
    if age < 3:
      print("your tickets are free")
    if age == 4 or age <= 12:
      print("your ticket is $10")
    else:
      print("your ticker is $15")

"""**7-6. Three Exits:**   
Write different versions of either Exercise 7-4 or 7-5 that do each of the following at least once:
- Use a conditional test in the while statement to stop the loop.
- Use an active variable to control how long the loop runs.
- Use a break statement to exit the loop when the user enters a 'quit' value.
"""

# code
while True:
    age = input("how old are you" )
    if age == 'quit':
      break
    if age < "3":
      print("your tickets are free")
    if age == "4" or age <= "12":
      print("your ticket is $10")
    else:
      print("your ticker is $15")

"""**7-7. Infinity:**   
Write a loop that never ends, and run it. (To end the loop, press CTRL-C or close the window displaying the output.)
"""

# code uuuuhhhhhh maybe????? not.

"""### Using a while Loop with Lists and Dictionaries
---
"""

# Moving Items from One List to Another

# Removing All Instances of Specific Values from a List

# Removing All Instances of Specific Values from a List

"""### TRY IT YOURSELF
---

**7-8. Deli:**   
Make a list called `sandwich_orders` and fill it with the names of various sandwiches. Then make an empty list called `finished_sandwiches`. Loop through the list of sandwich orders and print a message for each order, such as *I made your tuna sandwich*. As each sandwich is made, move it to the list of finished sandwiches. After all the sandwiches have been made, print a message listing each sandwich that was made.
"""

# code
sandwich_orders = ['meat', 'italian night club', 'sausage']
finished_sandwich = []
for name in sandwich_orders:
  print(f'I made your {name} sandwich')

"""**7-9. No Pastrami:**   
Using the list `sandwich_orders` from Exercise 7-8, make sure the sandwich `'pastrami'` appears in the list at least three times. Add code near the beginning of your program to print a message saying the deli has run out of pastrami, and then use a `while` loop to remove all occurrences of `'pastrami'` from `sandwich_orders`. Make sure no pastrami sandwiches end up in `finished_sandwiches`.
"""

# code
sandwich_orders = ['meat', 'italian night club', 'sausage', 'pastrami', 'pastrami', 'pastrami']
finished_sandwich = []
for name in sandwich_orders:
  print(f'I made your {name} sandwich')

"""**7-10. Dream Vacation:**   
Write a program that polls users about their dream vacation. Write a prompt similar to *If you could visit one place in the world, where would you go?* Include a block of code that prints the results of the poll.
"""

# code

destination = input("If you could visit one place in the world, where would you go? ")

while True:
    destination = input(prompt)
    if destination == 'quit':
        break
    else:
        print(destination)
print(destination)